- name: APT update and upgrade
  apt:
    cache_valid_time: 3600 #86400
    upgrade: yes

- name: Setup
  setup:

- name: Install basic tools
  apt:
    name:
      - acl  # for Ansible `become_user` with unprivileged user
      - curl
      - git  # Python script
      - htop
      - nano
      - nmon
      - rsync  # for ansible.posix.sychronize
      - vim
